[package]
name = "tauri_kit_audio"
version = "0.0.1"
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
cpal = "0.15"
rodio = { version = "0.19", default-features = false, features = ["mp3", "symphonia-mp3", "symphonia-wav", "vorbis"] }
anyhow = "1"
log = "0.4"
serde = { version = "1", features = ["derive"] }
ts-rs = "10"
